name = "sikmatye-api"
main = "worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[vars]
# SUPABASE_URL = ""
# GOOGLE_CLIENT_ID = ""
# GEMINI_API_KEY = ""

[secrets]
# SUPABASE_SERVICE_ROLE_KEY
# JWT_SECRET
