-- Disable RLS on all tables to follow "remove supabase rls support" request
ALTER TABLE franchises DISABLE ROW LEVEL SECURITY;
ALTER TABLE restaurants DISABLE ROW LEVEL SECURITY;
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_group_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE global_translations DISABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_translations DISABLE ROW LEVEL SECURITY;
ALTER TABLE translation_jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE translation_versions DISABLE ROW LEVEL SECURITY;
ALTER TABLE kitchen_canonical_names DISABLE ROW LEVEL SECURITY;
ALTER TABLE branch_translations DISABLE ROW LEVEL SECURITY;
ALTER TABLE franchise_translations DISABLE ROW LEVEL SECURITY;

-- If orders and tables exist (they usually do in this app)
ALTER TABLE tables DISABLE ROW LEVEL SECURITY;
ALTER TABLE dining_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE order_item_options DISABLE ROW LEVEL SECURITY;
ALTER TABLE baskets DISABLE ROW LEVEL SECURITY;
ALTER TABLE basket_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE cash_transactions DISABLE ROW LEVEL SECURITY;
