-- Add void auditing columns to pubic.orders table
ALTER TABLE public.orders 
ADD COLUMN IF NOT EXISTS voided BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS void_reason TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS voided_by TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS voided_at TIMESTAMPTZ DEFAULT NULL,
ADD COLUMN IF NOT EXISTS void_approved_by TEXT DEFAULT NULL;
